import { describe, expect, it } from 'vitest'
import { levels } from './levels'
import { lessons } from './curriculum'
import { drills } from './drills'
import { quizzes } from './quizzes'
import type { LevelId } from './types'

/**
 * Generates `docs/curriculum-map.md` — the whole curriculum on one page.
 *
 * Answering "what do we already teach about the serve?" otherwise means opening
 * 79 files. That is cheap for a human with a search box and expensive for an
 * agent reasoning about what to write next, which is exactly when the question
 * gets asked. The map is generated rather than hand-kept so it cannot drift:
 * `toMatchFileSnapshot` rewrites it locally and fails in CI when it is stale,
 * the same mechanism `contentIds.test.ts` uses to make renames visible.
 *
 * It also carries the ordering prefixes, so picking the next free slot for a new
 * lesson is a read rather than a directory listing.
 */

// Order lives in the filename, not in the compiled item, so recover it from the
// glob keys and join by id. Compiling every file just to read its prefix would
// be wasteful, so this glob is deliberately lazy — only the keys are used.
const paths = {
  lessons: import.meta.glob('/content/lessons/**/*.md'),
  drills: import.meta.glob('/content/drills/**/*.md'),
  quizzes: import.meta.glob('/content/quizzes/**/*.yml'),
}

function ordersById(modules: Record<string, unknown>): Map<string, string> {
  return new Map(
    Object.keys(modules).map((path) => {
      const [, order, id] = /^(\d+)-(.+)\.(?:md|yml)$/.exec(path.split('/').pop()!)!
      return [id!, order!]
    }),
  )
}

const order = {
  lessons: ordersById(paths.lessons),
  drills: ordersById(paths.drills),
  quizzes: ordersById(paths.quizzes),
}

function section<T extends { id: string; levelId: LevelId }>(
  heading: string,
  items: T[],
  levelId: LevelId,
  orders: Map<string, string>,
  line: (item: T) => [string, string],
): string {
  const forLevel = items.filter((item) => item.levelId === levelId)
  const rows = forLevel.map((item) => {
    const [meta, summary] = line(item)
    return `- **${orders.get(item.id)} · ${item.id}** — ${meta}\n  ${summary}`
  })
  return `### ${heading} (${forLevel.length})\n\n${rows.join('\n')}\n`
}

describe('curriculum map', () => {
  it('matches the generated map of every lesson, drill and quiz', async () => {
    const body = levels
      .map((level) =>
        [
          `## ${level.name}\n\n${level.tagline}\n`,
          section('Lessons', lessons, level.id, order.lessons, (lesson) => [
            `${lesson.title} · ${lesson.category}` +
              (lesson.drillIds?.length ? ` · drills: ${lesson.drillIds.join(', ')}` : ''),
            lesson.summary,
          ]),
          section('Drills', drills, level.id, order.drills, (drill) => [
            `${drill.title} · ${drill.skill} · ${drill.duration} · ${drill.equipment}`,
            drill.goal,
          ]),
          section('Quizzes', quizzes, level.id, order.quizzes, (quiz) => [
            `${quiz.title} · ${quiz.topic} · ${quiz.questions.length} questions`,
            quiz.description,
          ]),
        ].join('\n'),
      )
      .join('\n')

    const map = `# Curriculum map

<!--
  Generated by src/data/curriculumMap.test.ts from the files under content/.
  Do not edit this file: edit the content, then run \`npm run check:content\`.
  Numbers are the ordering prefixes in the filenames; ids are what user progress
  is keyed on.
-->

${body}`

    await expect(map).toMatchFileSnapshot('../../docs/curriculum-map.md')
  })
})
